[programs.localnet]
advent = "ke798ave2o7MMZkriRUPSCz1aLrrmPQY2zHdrikJ298"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/truble/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
